#!/bin/bash

#PBS -l nodes=1:ppn=20
#PBS -N myjob
#PBS -l walltime=00:10:00

WHEREIAM=$(pwd)

if [ $WHEREIAM == "/home/fbrand" ]
then
    cd "/home/fbrand/FHPC_2019-2020/Assignements"
elif
then
    echo "Are you on Ulysses?"
    exit
fi

echo "HelloWorld!"



